---
title: "Tablero Dashboard"
format: dashboard
---

# Carga-paquetes

```{r}
#| label: Carga de paquetes

library(tidyverse)
library(plotly)
library(DT)
library(sf)
library(leaflet)
library(leaflet.extras)
library(leafem)
library(dplyr)
library(viridis)
```

# Carga-datos

```{r}
#| label: Carga de datos
#| title: "Carga de datos a trabajar"

areas_conservacion <-
  st_read(
    dsn = "areas-conservacion.gpkg",
    quiet = TRUE
  )

especies <-
st_read(
  "especies-anfibios.csv",
  options = c(
      "X_POSSIBLE_NAMES=decimalLongitude",
      "Y_POSSIBLE_NAMES=decimalLatitude"   
    ))

registros <-
st_read(
  "registros-anfibios.csv",
  options = c(
      "X_POSSIBLE_NAMES=decimalLongitude",
      "Y_POSSIBLE_NAMES=decimalLatitude" 
    ))

st_crs(registros) <- 4326
```

# 1. Tabla cantidad de registros

```{r}
#| label: registros-lista-roja
#| title: "Tabla de registros por categoría presentes en la lista roja"

registros_x_especie <- 
  left_join(
    especies, registros, by = "species"
    )

presencia_lista_roja <- 
  registros_x_especie |>
  group_by(iucnRedListCategory) |>
  summarise(count = n()) |>
  arrange(desc(count)) 

colnames(presencia_lista_roja) <- 
  c(
    "Categoría", "Registros")

datatable(presencia_lista_roja,
          options = list(
            language = list(url = "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json")
          ))
```

# 2. Primer gráfico de barras 

```{r}
#| label: grafico-barras-categorias
#| title: "Gráico de barras de cantidad de especies en CR, EN y VU"

grafico_categorias <-
  presencia_lista_roja |>
  filter(Categoría == "CR" |
           Categoría == "VU" | Categoría == "EN") |>
  ggplot(aes(x = Categoría, y = Registros)) +
  geom_col() +
  labs(title = 'Cantidad de Especies en Categorías CR, EN y VU',
       x = 'Categoría',
       y = 'Registro de Especies') +
  theme_minimal()

ggplotly()

```

# 3. Mapa de riqueza en áreas de conservación 

```{r}
#| label: datos-mapa

riqueza_x_area <- 
  st_join(
    x = registros,
    y = dplyr::select(areas_conservacion, nombre_ac),
    join = st_within
  )

riqueza_x_anfibios <-
riqueza_x_area |>
  st_drop_geometry() |>
  group_by(nombre_ac) |>
  summarise(riqueza_x_anfibios = n_distinct(species, na.rm = TRUE))

areas_union_riqueza <-
  left_join(
    x = areas_conservacion,
    y = dplyr::select(riqueza_x_anfibios, nombre_ac, ),
    by = "nombre_ac"
  ) |>
  replace_na(list(riqueza_x_anfibios = 0))



```

```{r}
#| label: mapa-areas-conservacion
#| title: "Mapa leaflet de riqueza de anfibios en las áreas de conservación de CR"

colores_riqueza_especies <-
  colorNumeric(
    palette = "blues",
    domain = riqueza_x_anfibios$riqueza_x_anfibios,
    na.color = "transparent"
  )

# Paleta de colores de anfibios

colores_anfibios <- 
  colorFactor(
  palette = viridis(length(unique(riqueza_x_anfibios$riqueza_x_anfibios))), 
  domain = riqueza_x_anfibios$codigo_ac
)

# Mapa leaflet

leaflet() |>
  setView(
    lng = -84.19452,
    lat = 9.572735,
    zoom = 7) |>
  addTiles(group = "Mapa general (OpenStreetMap)") |>
  addProviderTiles(
    providers$Esri.WorldImagery, 
    group = "Imágenes satelitales (ESRI World Imagery)"
  ) |> 
  addPolygons(
    data = areas_union_riqueza,
    fillColor = ~ colores_anfibios(riqueza_x_anfibios$nombre_ac),
    fillOpacity = 0.6,
    color = "black",
    stroke = TRUE,
    weight = 1.0,
    popup = paste(
      paste("<strong>Área de conservación:</strong>", riqueza_x_anfibios$nombre_ac),
      paste("<strong>Riqueza de anfibios:</strong>", riqueza_x_anfibios$riqueza_x_anfibios),
      sep = '<br/>'
    ),
    group = "Riqueza de anfibios"
  ) |>
  addScaleBar(
    position = "bottomleft", 
    options = scaleBarOptions(imperial = FALSE)
  ) |>    
  addLegend(
    position = "bottomleft",
    pal = colores_anfibios,
    values = areas_union_riqueza$nombre_ac,
    group = "Riqueza de anfibios",
    title = "Riqueza de anfibios"
  ) |>
  addCircleMarkers(
    data = registros,
    stroke = F,
    radius = 4,
    fillColor = ~colores_anfibios(riqueza_x_anfibios$riqueza_x_anfibios),
    fillOpacity = 1.0,
    popup = paste(
      paste0("<strong>Especie: </strong>", riqueza_x_area$genus),
      paste0("<strong>Localidad: </strong>", areas_union_riqueza$nombre_ac ),
      paste0("<strong>Fecha: </strong>", riqueza_x_area$eventDate ),
      paste0("<strong>Fuente: </strong>", riqueza_x_area$institutionCode),
      paste0("<a href='", riqueza_x_area$occurrenceID, "'>Más información</a>"),
      sep = '<br/>'
    ),    
    group = "Registros de anfibios"
  )  |>  
  addLayersControl(
    baseGroups = c(
      "Mapa general (OpenStreetMap)", 
      "Imágenes satelitales (ESRI World Imagery)"
    ),
    overlayGroups = c(
      "Riqueza de anfibios",
      "Registros de presencia por área"
    )
  ) |>
  addResetMapButton() |>
  addSearchOSM() |>
  addMouseCoordinates() |>
  addFullscreenControl() |>
  hideGroup("Registros de anfibios") 
```

# 4 Gráfico de barras de riqueza de anfibios en áreas de conservación

```{r}
#| label: grafico-anfibios-areas
#| title: "Gráfico de barras acerca de la riqueza de anfibios en áreas de conservación"

grafico_riqueza <-
  riqueza_x_anfibios |>
  ggplot(aes(x = nombre_ac, y = riqueza_x_anfibios)) +
  geom_col() +
  labs(title = 'Riqueza de anfibios en distintas áreas',
       x = 'Áreas',
       y = 'Riqueza de anfibios') +
  theme_minimal()

ggplotly()
```

